### ISSUE TITLE
regression: building docker image startup takes > 5s

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#226]
- it's no longer streaming the logs from docker
- it takes multiple seconds even for a cached rebuild

**Comment by Arinono** [comment]
Can you provide your service, I cannot reproduce on my side ?

**Comment by wilzbach** [comment]
Take the `hashes` microservice mentioned in https://github.com/microservices/omg/issues/227. A cached `omg run` now takes 12s :/

**Comment by Arinono** [comment]
But still, once cached, I don't have this issue, it is immediate to rebuild the image.

**Comment by wilzbach** [comment]
Here's how it looks on my machine:

https://asciinema.org/a/CYV8oN9JtvDblA1ZcQVpHzHlG

**Comment by Arinono** [comment]
I might need some time to find what's happening here. I cannot reproduce the behavior.

Here my output using linux, as you do, instead of macOS (`Linux version 4.18.0-12-generic (buildd@lgw01-amd64-033) (gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)) #13-Ubuntu SMP Wed Nov 14 15:17:05 UTC 2018`) :
https://asciinema.org/a/4S5TE8Pl3S0gHPCxbiJpt7VLk

**Comment by StoryscriptHuman** [comment]
This shouldn't be an issue in the new dawn releases
